name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:run
      - run: npx tsx main.ts
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libreoffice
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npx tsx vrt/genpptx.ts
      - run: soffice --headless --convert-to png --outdir ./vrt actual.pptx
      - run: npx tsx vrt/vrt.ts
